language: node_js
node_js:
  - "4.2.3"
sudo: false
before_install:
  - chmod +x gradlew
  - npm install -g gulp
  - npm install -g bower
install:
  - npm install
  - bower install
before_script:
  - gulp build
  - ./gradlew test
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
