# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    messages:
        basename: classpath:/i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML
    social:
        # see https://developers.google.com/+/web/signin/server-side-flow#step_1_create_a_client_id_and_client_secret
        google:
            clientId: YOUR_ID
            clientSecret: YOUR_SECRET

        # see https://developers.facebook.com/docs/facebook-login/v2.2
        facebook:
            clientId: YOUR_ID
            clientSecret: YOUR_SECRET

        # see https://apps.twitter.com/app/
        twitter:
            clientId: YOUR_ID
            clientSecret: YOUR_SECRET

security:
    basic:
        enabled: false

# ===================================================================
# p2p-webtv specific properties
# ===================================================================

p2p-webtv:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    #cors: #By default CORS are not enabled. Uncomment to enable.
        #allowed-origins: "*"
        #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        #allowed-headers: "*"
        #exposed-headers:
        #allow-credentials: true
        #max-age: 1800
    mail:
        from: p2p-webtv@localhost
    security:
        rememberme:
            key: YOUR_KEY
    swagger:
        title: ppwebtv API
        description: ppwebtv API documentation
        version: 0.1.0
        termsOfServiceUrl:
        contact:
        license:
        licenseUrl:
    movieDatabase:
        apiKey: YOUR_API_KEY
    social:
        redirectAfterSignIn: "/#/home"
